### ISSUE TITLE
转换模型后无法读取

### ISSUE THREAD

**Issue by LemonQC** [DA-southampton/Read_Bert_Code#2]
Traceback (most recent call last):
  File "run_classifier.py", line 522, in <module>
    main()
  File "run_classifier.py", line 460, in main
    config = config_class.from_pretrained(args.config_name if args.config_name else args.model_name_or_path, num_labels=num_labels, finetuning_task=args.task_name)
  File "/home/cirlab1/userdir/liujin/NLP/Read_Bert_Code/bert_read_step_to_step/transformers/configuration_utils.py", line 154, in from_pretrained
    config = cls.from_json_file(resolved_config_file)
  File "/home/cirlab1/userdir/liujin/NLP/Read_Bert_Code/bert_read_step_to_step/transformers/configuration_utils.py", line 189, in from_json_file
    return cls.from_dict(json.loads(text))
  File "/home/cirlab1/anaconda3/lib/python3.6/json/__init__.py", line 349, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte**

**Comment by DA-southampton** [comment]
可以使用Python3

**Comment by JaneHobi** [comment]
请问是怎么解决这个问题的呢，我也遇到了相同的问题，我的环境是python3.6

**Comment by FightAllDays** [comment]
您好，请问您的问题解决了嘛。。。我使用的是3.7 也会出现这个问题。。。

**Comment by FightAllDays** [comment]
> 请问是怎么解决这个问题的呢，我也遇到了相同的问题，我的环境是python3.6

您好，请问您的问题解决了嘛。。。我使用的是3.7 也会出现这个问题。。。

**Comment by XJZhuang** [comment]
怎么解决，我也遇到这个问题，我的环境是python3.7
